const prefix = '@@pages/schemaView';

export const GET_BUILDING_AREAS = `${prefix}/GET_BUILDING_AREAS`;
export const GET_BUILDING_AREAS_COMPLETED = `${GET_BUILDING_AREAS}_COMPLETED`;
export const GET_BUILDING_AREAS_FAILED = `${GET_BUILDING_AREAS}_FAILED`;

export const SAVE_BUILDING_AREA = `${prefix}/SAVE_BUILDING_AREA`;
export const SAVE_BUILDING_AREA_COMPLETED = `${SAVE_BUILDING_AREA}_COMPLETED`;
export const SAVE_BUILDING_AREA_FAILED = `${SAVE_BUILDING_AREA}_FAILED`;
